### ISSUE TITLE
It would be nice if there was a simple README for local play.

### ISSUE THREAD

**Issue by caranha** [alanxoc3/radico8#29]
I imagine that I could probably figure out how to do it myself if I spent some time on it, but it would be really great if there was a readme (or even better, a script), explaining how one would go around to have radico8 play locally.

Some use cases:
- The youtube stream is down;
- I want to listen to radico8, but my intranet blocks youtube for whatever reason;
- I want to host the stream in my webpage;
- I got no internet, but I want to play locally;

Thank you for this cool project!

**Comment by alanxoc3** [comment]
Just noticed the youtube stream went down again... Sorry about that.

The webradio has never gone down though + it's lower latency: http://radico8.xoc3.io

Working on another comment to describe local play...

**Comment by alanxoc3** [comment]
Ok, I updated the readme with instructions for local play (I changed some scripts to make it a bit easier). Let me know how it works out for you. Local play is pretty lightweight, the only overhead is running pico-8.

There isn't much of a UI right now for local play, but it might be cool to have one eventually for connecting the local radio to a TV or something similar.
